### ISSUE TITLE
Часовой пояс

### ISSUE THREAD

**Issue by DeriksonTM** [reosfire/TemporaryWhiteList#5]
Можно ли как то в плагине сделать часовой пояс с системы? а то он отображается в PM, не 17:00 а 05:00

**Comment by reosfire** [comment]
Да, это возможно. В конфиге нужно установить
`DateTimeFormat: "[dd MM yyyy] HH:mm:ss"`
т.е написать формат для часов в верхнем регистре.

**Comment by DeriksonTM** [comment]
Спасибо большое! ♥♥♥
