### ISSUE TITLE
Кик игрока

### ISSUE THREAD

**Issue by DeriksonTM** [reosfire/TemporaryWhiteList#6]
Можно ли как то сделать чтобы игрока кикало при завершении времени его вайт листа? или эт не реализованно здесь еще?

**Comment by reosfire** [comment]
Это уже реализовано. Если у вас это не работает, то перепроверите, больше ли нуля `SubscriptionEndCheckTicks`, и консоль на наличие ошибок от twl.

**Comment by DeriksonTM** [comment]
![image](https://user-images.githubusercontent.com/92043849/211209547-94618d96-03cb-4a22-b8bd-e1071dec8d17.png)

**Comment by DeriksonTM** [comment]
https://pastebin.com/ZmB3Gke6 Ошибок в консоли нет

**Comment by DeriksonTM** [comment]
Purpur 1.19.2

**Comment by DeriksonTM** [comment]
выставил первый параметр на 0, правильно сделал? все работает щас

**Comment by reosfire** [comment]
Вообще - не совсем. Он теперь больше лагает. С теми настройками, которые вы
мне скинули он раз в 5 секунд проверял игроков на то, закончился у них
вайтлист или нет. Возможно это конфликт с каким то другим плагином.
У вас этот баг лекго воспроизводился?

вс, 8 янв. 2023 г., 20:40 DeriksonTM ***@***.***>:

**Comment by DeriksonTM** [comment]
Сервер чистый, только 1 ваш плагин

**Comment by DeriksonTM** [comment]
там было 100, но игрока не кикало, что тогда написать?

**Comment by reosfire** [comment]
Можете пожалуйста воспроизвсти этот баг, и скинуть целиком всю папку с сервером. У меня этот баг не удаётся воспроизвести.

**Comment by DeriksonTM** [comment]
извиняюсь за долгий ответ, может проблема в ядре? у меня последний purpur на 1 19 2

**Comment by reosfire** [comment]
> извиняюсь за долгий ответ, может проблема в ядре? у меня последний purpur на 1 19 2

Проблема всё еще не решена?

**Comment by DeriksonTM** [comment]
Я обновился до 1.19.3 там все вроде нормально работает, тиков так же 100 выставлено.
