### ISSUE TITLE
Exception during pool initialization.

### ISSUE THREAD

**Issue by DeriksonTM** [reosfire/TemporaryWhiteList#8]
https://pastebin.com/7YLr6HxE help pls
error

Purpur 1.19.3

**Comment by DeriksonTM** [comment]
и еще вопрос, на сколько всё будет плохо если я выставлю RefreshAfter: 0?

**Comment by reosfire** [comment]
> и еще вопрос, на сколько всё будет плохо если я выставлю RefreshAfter: 0?

Если используете papi то в таком случае, каждое обновление плейсхолдера будет вызывать запрос к бд

**Comment by reosfire** [comment]
> https://pastebin.com/7YLr6HxE help pls error
> 
> Purpur 1.19.3

Если немного погуглить можно найти это: https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed

Мне самым адекватным кажется ответ: [Torsten Ojaperv](https://stackoverflow.com/a/53300421)

**Comment by DeriksonTM** [comment]
> > и еще вопрос, на сколько всё будет плохо если я выставлю RefreshAfter: 0?
> 
> Если используете papi то в таком случае, каждое обновление плейсхолдера будет вызывать запрос к бд

У меня просто ситуация здесь вот какая, я имею 3 сервера. Velocity \ AuthMe \ Survival

Я хочу чтобы игрока без доступа кикало уже на авторизации. 
Я установил 2 плагина на выживание и авторизацию.

Игроку выдаю доступ на авторизации, он заходит на выживалку спокойно. Там мне плагин нужен для papi, чтобы игрок мог отследить сколько у него еще действует вайт лист. Но моментами бывает проблема, у игрока есть доступ на авторизации, а в чат пишет что нету доступа к серверу выживания, там в бд еще не обновилось инфа о доступе. Я как понял это RefreshAfter: 60. Ситуация бывает в случаях если продлевать вайт лист за несколько секунд до окончания. На сколько критично будет если выставлять RefreshAfter: 1? Но на сервере выживания у меня 3 плейсхолдера, обратный отчёт, дата получения и дата окончания доступа. 

Можно еще как нибудь Ваш дискорд получить чтобы связаться? Можете меня сами добавить если не хотите здесь публиковать его - Дэриксон™#7094
