### ISSUE TITLE
Импорт вайт листа с minecraft

### ISSUE THREAD

**Issue by Energobro** [reosfire/TemporaryWhiteList#9]
Добрый день, мне не понятно как импортировать список игроков с обычного вайт-листа майнкрафта, инструкции нормальной нет и мне не понятно что нужно сделать чтобы  все игроки перенеслись. Подскажите пожалуйста команду с полными аргументами как сделать это правильно, спасибо

**Comment by reosfire** [comment]
Добрый день. 
Вот эта команда долджна импортировать всех игроков из майнкрафт вайтлиста, и выдать им 0 секунд в вайтлисте + перманентную подписку: **/twl import minecraft 0:s true**
А эта уже выдаст всем по одному дню: **/twl import minecraft 1:d false**

**Comment by Energobro** [comment]
спасибо вам огромное, отличный плагин

**Comment by Energobro** [comment]
А будет ли возможность в новой версии добавить поддержку RCON? чтобы о добавлении игрока писалось туда тоже, а то команда прописывается а сообщения о добавлении только в обычную консоль отправлется

**Comment by reosfire** [comment]
Частичная поддержка RCON уже есть. Для этого просто необходимо использовать twl-sync вместо twl

**Comment by reosfire** [comment]
У неё пока доступны Add Set Check Remove

**Comment by Energobro** [comment]
огромное спасибо!
лучший плагин
